const products = [
  {
    id: 'rec43w3ipXvP28vog',
    title: 'Kombo Laham',
    company: 'Kombo',
    image: 'img/kombo laham.jpg',
    price: 5.99,
    order: 'Add',
  },
  {
    id: 'rec4f2RIftFCb7aHh',
    title: 'Kudura Samaka',
    company: 'Kudura',
    image: 'img/kudura samaka.jpg',
    price: 6.55,
    order: 'Add',
  },
  {
    id: 'rec8kkCmSiMkbkiko',
    title: 'Shurba Laham',
    company: 'Shurba',
    image: 'img/shurba.jpg',
    price: 18.88,
    order: 'Add',
  },
  {
    id: 'recBohCqQsot4Q4II',
    title: 'Shurba Jidada',
    company: 'Shurba',
    image: 'img/shurba jidada.jpg',

    price: 20.14,
    order: 'Add',
  },
  {
    id: 'recDG1JRZnbpRHpoy',
    title: 'Shurba Samaka',
    company: 'Shurba',
    image: 'img/shurba samaka.jpg',

    price: 24.90,
    order: 'Add',
  },
  {
    id: 'recNWGyP7kjFhSqw3',
    title: 'Shaiya Laham',
    company: 'Shaiya',
    image: 'img/shaiya laham.jpg',
    price: 20.01,
    order: 'Add',
  },
  {
    id: 'recZEougL5bbY4AEx',
    title: 'Asida Maize',
    company: 'Asida',
    image: 'img/asida maize.jpg',
    price: 6.21,
    order: 'Add',
  },
  {
    id: 'recjMK1jgTb2ld7sv',
    title: 'Shaiya Samaka',
    company: 'Shaiya',
    image: 'img/shaiya samaka.jpg',
    price: 26.77,
    order: 'Add',
  },
  {
    id: 'recmg2a1ctaEJNZhu',
    title: 'Asida Babrock',
    company: 'Asida',
    image: 'img/asida babrock.jpg',
    price: 6.95,
    order: 'Add',
  },
  {
    id: 'recvKMNR3YFw0bEt3',
    title: 'Shaiya Jidada',
    company: 'Shaiya',
    image: 'img/shaiya jidada.jpg',
    price: 24.88,
    order: 'Add',
  },
  {
    id: 'recxaXFy5IW539sgM',
    title: 'Croppa',
    company: 'Croppa',
    image: 'img/cropa.jpg',
    price: 6.19,
    order: 'Add',
  },
  {
    id: 'recyqtRglGNGtO4Q5',
    title: 'Shaiya Mixed',
    company: 'Shaiya Mixed',
    image: 'img/mixed.jpg',
    price: 25.19,
    order: 'Add',
  },
];
